export const defaultSiteFormState = {
    site_name: "",
    site_key: "",
    primary_domain: "",
    company_name: "",
    domains: [] as string[],
    is_active: true,
    read_only: false,
    logo: "",
    small_icon_url: "",
    shop: "",
    access_token: "",
    api_version: "",
    webhook_secret: "",
    api_key: "",
    api_secret: "",
    enableDailyCo: false,
    enableDocmanJobs: false,
    enableMailing: false,
    enableLexisNexis: false,
    enableKlaviyo: false,
    enableProductFilter: false,
    dailyCoSecretKey: "",
    dailyCoDomain: "",
    dailyCoWebhookHMAC: "",
    dailyCoWebhookUrl: "",
    dailyCoSubdomain: "",
    jobsApiToken: "",
    mailHost: "",
    mailPort: "",
    mailUsername: "",
    mailPassword: "",
    mailFromName: "",
    mailFromAddress: "",
    senderOverrides: {} as Record<string, string>,
    lexisNexisUrl: "",
    lexisNexisUsername: "",
    lexisNexisPassword: "",
    klaviyoApiKey: "",
    product_ids: ""
};
